package com.example.orderservice.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.List;

/**
 * Entity Class to represent the Product table
 * Generated by CreateEntityClass, Oracle Data Model 12.1.1.4
 *
 * @author Oracle DF
 */
@Entity
@Table (name = "products")
public class Product {

    /**
     * The id of the product
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonIgnore
    private Long productId;

    /**
     * The id of the product
     */
    @Transient
    private Long id;

    /**
     * The name of the product
     */
    @Column (name = "product_name")
    @NotNull
    private String productName;
    /**
     * The price of the product
     */
    @Column (name = "price")
    @NotNull
    private BigDecimal price;

    /**
     * The items associated with the product
     */
    @OneToMany (mappedBy = "product", cascade = CascadeType.ALL)
    @JsonIgnore
    private List<Item> items;

    /**
     * Get the id of the product
     * @return the id of the product
     */
    public Long getId() {
        return id;
    }

    /**
     * Set the id of the product
     * @param id the id of the product
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get the name of the product
     * @return the name of the product
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Set the name of the product
     * @param productName the name of the product
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * Get the price of the product
     * @return the price of the product
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Set the price of the product
     * @param price the price of the product
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Get the items associated with the product
     * @return the items associated with the product
     */
    public List<Item> getItems() {
        return items;
    }

    /**
     * Set the items associated with the product
     * @param items the items associated with the product
     */
    public void setItems(List<Item> items) {
        this.items = items;
    }
}

